name: CI

on: 
  push:
  pull_request:
    types: [opened]

jobs:
  sunstone:
    name: Condenser/Rails Test
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        ruby-version:
          - 3.2
          - 3.3
          - 3.4
          - 3.5.0-preview1
        rails-version:
          - 7.1
          - 7.2
          - 8.0
        exclude:
          - rails-version: '7.1'
            ruby-version: '3.5.0-preview1'
          - rails-version: '7.2'
            ruby-version: '3.5.0-preview1'

    steps:
      - uses: actions/checkout@v4

      - run: |
          echo 'gem "rails", "${{ matrix.rails-version }}"' >> Gemfile

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically

      - run: bundle exec rake test