name: CI

on: 
  push:
  pull_request:
    types: [opened]

jobs:
  sunstone:
    name: Condenser/Rails Test
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        rails-version:
          - 7.0.8
          - 7.1.2
        ruby-version:
          - 3.1
          - 3.2
          - 3.3

    steps:
      - uses: actions/checkout@v4

      - run: |
          echo 'gem "rails", "${{ matrix.rails-version }}"' >> Gemfile

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically

      - run: bundle exec rake test